### ISSUE TITLE
Confirmation popups operating incorrectly

### ISSUE THREAD

**Issue by swapneils** [40ants/reblocks-ui#7]
As an extension to the reblocks tutorial, I tried to add a confirmation dialogue to the form for adding tasks to the todo list.

```
(defmethod reblocks/widget:render ((task-list task-list))
  (reblocks/html:with-html
   (:h1 "Tasks")
    (map nil (lambda (task) (reblocks/widget:render task)) (tasks task-list))
   ;; (loop for task in (tasks task-list) do
   ;;       (reblocks/widget:render task))
   (reblocks-ui/form:with-html-form (:post (lambda (&key title &allow-other-keys)
                                             (add-task task-list title))
                                     :requires-confirmation-p t
                                     :confirm-question "are you sure you're ready to do more tasks?"
                                     )
     (:input :type "text"
      :name "title"
      :placeholder "Task's title")
     (:input :type "submit"
      :value "Add"))))
```

However, this instead results in a permanently-visible new section with the confirmation dialogue in h1 and an "ok" and "cancel" button. This section is independent of the form itself, and if ok is selected then a task with an empty title is added to the list. 

![image](https://github.com/40ants/reblocks-ui/assets/32959209/ebd919ea-616e-4c79-8cf1-2c9f133155f3)

Through console inspection it appears that Foundation was not properly imported. My code seems structurally identical to the example in docs/form.lisp, so I assume this is another manifestation of the many online issues re: importing foundation

Additionally, I tried manually importing foundation with the following code in the browser console (and then copy-pasting the script code for hiding or showing the confirmation dialogue):
```
var scriptTag = document.createElement("script");
undefined
scriptTag.setAttribute("src", "https://cdnjs.cloudflare.com/ajax/libs/foundation/6.7.4/js/foundation.min.js");
undefined
document.body.appendChild(scriptTag);
```
The confirmation dialogue was still default-visible afterwards, but it _did_ at least get selected when you tried to add a task, and disappeared when pressing "cancel". However, pressing "ok" created an empty task instead of using the name in the textbox. Looking into the browser console, it seems that the confirmation dialogue was in a different form from the actual textbox, and did not have access to the original form's information.

In addition, the calls to update the task-list widget constantly added new confirmation-dialogues without removing the old ones from the page (I noticed this was also the case for some script tags importing jquery.js and jquery-seq.js from the reblocks repository), although the script tag with the show/close functions was updated correctly to match the latest confirmation block. The non-most-recent blocks would no longer be hidden by clicking "cancel", though "ok" still added an empty task.

## Potential solutions

1. Update the \*foundation-dependencies\* variable in reblocks-ui/core.lisp to foundation version 6.7.4
2. Import the \*foundation-dependencies\* in the generated HTML/JS code for %render-confirmation-popup. 
3. Change the confirmation popup code to submit the contents of the original form, rather than of the confirmation popup form.
4. Figure out how to delete the old confirmation popups when updating the containing widget.

Note: 3. and 4. may have the same answer of just moving the popup _inside_ at the end of the widget div, rather than placing it right afterwards (which is currently the case according to the browser console).

I'm fairly new to common lisp in general, as well as JS (though I've had to slog through a project with the latter recently), and currently have no idea how to do any of these except 1., but they seem like they would be enough to get this working.

**Comment by svetlyak40wt** [comment]
Hmm, I have to find time for investigation.

Can you dump all your code into a temporary repository or gist?

**Comment by swapneils** [comment]
https://gist.github.com/swapneils/9cb994765f1fd83c15bb32a847ab0cbf

Contains the full file, which replicates the issue. requires-confirmation-p is currently commented, and javascript is inserted ("return confirm(...)") to imitate the "confirmation" functionality.

**Comment by svetlyak40wt** [comment]
I've tested the code.

The problem is that you don't inherit your widget from `reblocks-ui:ui-widget`. When it is inherited, Foundation js is loaded. Here is my fork of the gitst with some fixes:

https://gist.github.com/svetlyak40wt/517e3e37f97261547262e4a58312a8f3

**Comment by svetlyak40wt** [comment]
I'm planning to remake UI library and will do reblocks-ui2 with completely different API. Hope to solve such problems there.
